# 這個檔案是 Spring Boot 的設定檔，用來設定伺服器、資料庫、Kafka 和 JWT 的相關資訊。

server:
  port: 8082
  # 伺服器的埠號，設定為 8082

spring:
  datasource:
    url: jdbc:postgresql://db:5432/orderdb
    # 資料庫的連線 URL，指向 PostgreSQL 的 orderdb 資料庫
    username: orderuser
    # 資料庫的使用者名稱
    password: orderpass
    # 資料庫的密碼
  jpa:
    hibernate:
      ddl-auto: update
      # 自動更新資料庫結構
    show-sql: true
    # 顯示執行的 SQL 語句
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # 使用 PostgreSQL 的資料庫方言
  kafka:
    bootstrap-servers: kafka:9092
    # Kafka 的伺服器位置
    consumer:
      group-id: order-consumer-group
      # Kafka 消費者的群組 ID

jwt:
  secret: "abcdefghijklmnopqrstuvwxyz123456abcdefghijklmnopqrstuvwxyz123456"
  # JWT 的加密密鑰
  expiration: 3600000
  # JWT 的有效時間（毫秒），這裡設定為 1 小時
